# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source "https://rubygems.org"
ruby "2.2.2", :engine => "jruby", :engine_version => "9.0.4.0"
gem 'middleman', '~> 4.0.0'
gem 'middleman-compass', '~> 4.0.0.rc.1'
gem "compass", "~> 1.0.1"
gem "susy", "~> 2.2.3"
gem "breakpoint", "~> 2.5.0"
gem "middleman-syntax", "~> 2.1.0"
gem "middleman-minify-html", "~> 3.4.1"
# Live-reloading plugin
gem "middleman-livereload", "~> 3.4.2"
